server:
  port: ${PORT:8761} # Use PORT environment variable, default to 8761

spring:
  application:
    name: service-registry

eureka:
  instance:
    hostname: ${HOSTNAME:eurekaserver} # Use HOSTNAME environment variable, default to eurekaserver
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka