server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: Event-service
          uri: lb://Event-module
          predicates:
            - Path=/event/**
        - id: user-microservice
          uri: lb://user-microservice
          predicates:
            - Path=/user/**
        - id: notification-module
          uri: lb://notification-module
          predicates:
            - Path=/notification/**