# This file defines a Kubernetes Deployment and Service for the apigateway microservice.

# The Deployment object ensures that a specified number of pod replicas are running at any given time.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway          # Name of the Deployment
  labels:
    app: apigateway         # Labels used to identify the Deployment

spec:
  replicas: 1               # Number of pod replicas to run (Can be adjusted to meet your needs !)
  selector:
    matchLabels:
      app: apigateway       # Selector to match pods with the label 'app: apigateway'

  template:
    metadata:
      labels:
        app: apigateway     # Labels assigned to the pods created by this Deployment

    spec:
      containers:
      - name: apigateway                    # Name of the container within the pod
        image: amineromdhani/apigateway:1.0  # Container image to use
        imagePullPolicy: Always             # Always pull the latest image version
        ports:
        - containerPort: 8060               # Port on which the container listens

---
# The Service object defines how to access the apigateway application within the Kubernetes cluster.
apiVersion: v1
kind: Service
metadata:
  name: apigateway          # Name of the Service
spec:
  selector:
    app: apigateway         # Selector to match pods with the label 'app: apigateway'

  ports:
    - protocol: TCP         # Protocol used by the service (TCP)
      port: 8060            # Port exposed by the Service
      targetPort: 8060      # Port on which the container is listening (should match the containerPort in the Deployment)
