# This file defines a Kubernetes Deployment and Service for MongoDB.

# Deployment for MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb               # Name of the Deployment
  labels:
    app: mongodb             # Label to identify pods managed by this Deployment
spec:
  replicas: 1                 # Number of pod replicas to run
  selector:
    matchLabels:
      app: mongodb            # Selector to match pods with the label 'app: mongodb'

  template:
    metadata:
      labels:
        app: mongodb          # Labels assigned to the pods created by this Deployment

    spec:
      containers:
      - name: mongodb                          # Name of the container within the pod
        image: mongo                           # Container image to use
        ports:
        - containerPort: 27017                 # Port MongoDB is listening on

# Service for MongoDB
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb               # Name of the Service
spec:
  selector:
    app: mongodb             # Selector to match pods with the label 'app: mongodb'

  ports:
    - protocol: TCP
      port: 27017            # Port exposed by the Service for MongoDB
      targetPort: 27017      # Port on which MongoDB is listening within the pods
  type: NodePort             # Exposes the Service on a randomly selected port on each node

