apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb                    # Name of the Deployment
  labels:
    app: mysqldb                   # Label to identify the Deployment
spec:
  replicas: 1                      # Number of replicas (pods) to create
  selector:
    matchLabels:
      app: mysqldb                 # Select pods with the app label set to mysqldb
  template:
    metadata:
      labels:
        app: mysqldb               # Labels for pods created by this template
    spec:
      containers:
      - name: mysqldb               # Container name
        image: mysql                # MySQL Docker image
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"              # Allow empty password for MySQL root user
        ports:
        - containerPort: 3306       # Port on which MySQL server listens
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /home/mysql    # Mount path within the MySQL container
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc      # Reference the PersistentVolumeClaim for storage
