apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql                   # Name of the PersistentVolume
spec:
  capacity:
    storage: 1Gi                   # Storage capacity of the PersistentVolume
  volumeMode: Filesystem           # Specifies the volume mode as Filesystem
  accessModes:
    - ReadWriteOnce                # Defines the access mode as ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Specifies the reclaim policy for the PersistentVolume
  hostPath:
    path: /home/mysql-data        # Specifies the host path where the volume data will be stored
