# This file defines a Kubernetes Deployment and Service for the reviewservice microservice.

# The Deployment object ensures that a specified number of pod replicas are running at any given time.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewservice        # Name of the Deployment
  labels:
    app: reviewservice       # Labels used to identify the Deployment

spec:
  replicas: 1                # Number of pod replicas to run
  selector:
    matchLabels:
      app: reviewservice     # Selector to match pods with the label 'app: reviewservice'

  template:
    metadata:
      labels:
        app: reviewservice   # Labels assigned to the pods created by this Deployment

    spec:
      containers:
      - name: reviewservice                    # Name of the container within the pod
        image: amineromdhani/reviewservice:1.0 # Container image to use
        imagePullPolicy: Always                # Pull policy to always pull the latest image
        ports:
        - containerPort: 8090                 # Port on which the container listens

---
# The Service object defines how to access the reviewservice application within the Kubernetes cluster.
apiVersion: v1
kind: Service
metadata:
  name: reviewservice        # Name of the Service
spec:
  selector:
    app: reviewservice       # Selector to match pods with the label 'app: reviewservice'

  ports:
    - protocol: TCP          # Protocol used by the service (TCP)
      port: 8090             # Port exposed by the Service
      targetPort: 8090       # Port on which the container is listening (should match the containerPort in the Deployment)
