# DATABASE
spring:
  application:
    name: admin-microservice
  config:
    import: "optional:configserver:http://localhost:8088"
  mail:
    host: smtp.gmail.com
    port: 587
    username: racem.messaoudi@gmail.com
    password: vqslyxehzolbwyie
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true