# DATABASE
spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/Microservice-Nadine?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:



  # JPA / HIBERNATE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka


  #mail sender
