# DATABASE
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Microservice-Nadine?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:

  mail:
    host: smtp.gmail.com
    port: 587
    username: racem.messaoudi@gmail.com
    password: vqslyxehzolbwyie
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # JPA / HIBERNATE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


  #mail sender
