# Tomcat server properties
server:
  port: 8060


# eureka discovery client config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Spring cloud gateway config
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"  # Allow all headers
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: notification-module
          uri: lb://notification-module
          predicates:
            - Path=/notification/**
        - id: user-microservice
          uri: lb://user-microservice
          predicates:
            - Path=/api/v1/**
        - id: admin-microservice
          uri: lb://admin-microservice
          predicates:
            - Path=/admin/**
