### DATABASE ###
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Event?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  ### JPA / HIBERNATE ###
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.MySQL5Dialect

  ### mail ###
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: medmohamed.maalej@gmail.com
    password: tygr giug wjai oyva
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
