spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/notification_system
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: "aaa"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ramdhaniahmedamine@gmail.com
    password: eozp nmwb ktlx yivu
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

server:
  servlet:
    context-path: /notification
  port: 8094