spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/notification_system
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: "aaa"
  mail:
    host: smtp.gmail.com
    port: 587
    username:  example@gmail.com # Replace it with your email
    password: XXXX YYYY ZZZZ AAAA # Replace it with your gmail password ( app password)
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

server:
  servlet:
    context-path: /notification
  port: 8094