spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/resourcems
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
