spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reviews?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  #mail:
  #  host: smtp.gmail.com
    #   port: 587
    #  username: your-email@gmail.com
    #  password: your-password
      #  properties:
      #   mail:
      #    smtp:
      #     auth: true
            #    starttls:
    #   enable: true
  ### JPA / HIBERNATE ###
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    format:
      date: yyyy-MM-dd
server:
  port: 8090
springfox:
  documentation:
    swagger-ui:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
