spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  application:
    name: user-microservice
  data:
    mongodb:
      uri: mongodb://mongodb:27017/user_microservice_db
  mail:
    host: localhost
    port: 1025
    username: jalel
    password: jalel
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

logging:
  level:
    org:
      springframework:
        web: DEBUG

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000 # 7 days
      refresh-token:
        expiration: 2592000000 # refresh-token expiration time (30 days)
  mailing:
    frontend:
      activation-url: "http://localhost:4200/activate-account"

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka